/**
 * Generates src/styles/theme.css from design-tokens.json.
 *
 * Emits a Tailwind v4 `@theme {}` block (namespaced tokens that become real
 * utility classes: --color-accent -> bg-accent/text-accent, --text-2xl ->
 * text-2xl, --radius-lg -> rounded-lg, --spacing-4 -> p-4, etc.) followed by
 * a `:root {}` block of purpose-level aliases used anywhere raw var()
 * references are needed.
 *
 * Single source of truth: design-tokens.json. Never edit theme.css by hand.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'src/styles');
mkdirSync(outDir, { recursive: true });

const tokens = JSON.parse(readFileSync(join(root, 'design-tokens.json'), 'utf8'));

const t = tokens.typography;
const c = tokens.color;

/* line-height for each display size */
const typeLineHeights = { xs: 1.5, sm: 1.5, md: 1.5, base: 1.5, lg: 1.65, xl: 1.4, '2xl': 1.3, '3xl': 1.2, '4xl': 1.12, '5xl': 1.05 };

const lines = [];
lines.push('/* ================================================================');
lines.push('   Generated by scripts/generate-theme.mjs from design-tokens.json');
lines.push('   Tailwind v4 @theme + purpose aliases. DO NOT EDIT BY HAND.');
lines.push('   ================================================================ */');
lines.push('');

/* ---------------- @theme ---------------- */
lines.push('@theme {');

// Fonts
lines.push(`  --font-sans: ${t.family.sans};`);

// Font sizes
for (const [k, v] of Object.entries(t.size)) {
  lines.push(`  --text-${k}: ${v};`);
  lines.push(`  --text-${k}--line-height: ${typeLineHeights[k] ?? 1.5};`);
}

// Weights
for (const [k, v] of Object.entries(t.weight)) {
  lines.push(`  --font-weight-${k}: ${v};`);
}

// Line heights
for (const [k, v] of Object.entries(t.lineHeight)) {
  lines.push(`  --leading-${k}: ${v};`);
}

// Spacing
for (const [k, v] of Object.entries(tokens.spacing)) {
  lines.push(`  --spacing-${k}: ${v};`);
}

// Radius
for (const [k, v] of Object.entries(tokens.radius)) {
  lines.push(`  --radius-${k}: ${v};`);
}

// Shadows
for (const [k, v] of Object.entries(tokens.shadow)) {
  lines.push(`  --shadow-${k}: ${v};`);
}

// Color ramps (raw)
for (const [ramp, colors] of Object.entries(c)) {
  if (ramp === 'semantic') continue;
  for (const [k, v] of Object.entries(colors)) {
    lines.push(`  --color-${ramp}-${k}: ${v};`);
  }
}

// Semantic status colors -> friendly Tailwind token names
for (const name of ['success', 'warning', 'danger', 'info']) {
  const s = c.semantic[name];
  lines.push(`  --color-${name}: ${s.solid};`);
  lines.push(`  --color-${name}-soft: ${s.bg};`);
  lines.push(`  --color-${name}-ink: ${s.text};`);
  lines.push(`  --color-${name}-border: ${s.border};`);
}

// Purpose tokens (the contract components use)
const purpose = {
  ink: c.neutral['900'],
  'ink-secondary': c.neutral['600'],
  'ink-muted': c.neutral['500'],
  accent: c.primary['500'],
  'accent-strong': c.primary['600'],
  'accent-deep': c.primary['700'],
  'accent-soft': c.primary['50'],
  teal: c.secondary['400'],
  'teal-soft': c.secondary['50'],
  'teal-deep': c.secondary['900'],
  gold: c.gold['400'],
  'gold-soft': c.gold['50'],
  'gold-deep': c.gold['800'],
  'surface-page': c.neutral['0'],
  'surface-raised': c.neutral['0'],
  'surface-subtle': c.neutral['100'],
  line: c.neutral['200'],
  'line-strong': c.neutral['300'],
};
for (const [name, val] of Object.entries(purpose)) {
  lines.push(`  --color-${name}: ${val};`);
}

lines.push('}');
lines.push('');

/* ---------------- :root purpose aliases ---------------- */
lines.push(`:root {
  /* Purpose-level aliases (duplicated from the @theme tokens above for raw var() use) */

  --surface-page: var(--color-surface-page);
  --surface-raised: var(--color-surface-raised);
  --surface-subtle: var(--color-surface-subtle);
  --surface-primary-soft: var(--color-accent-soft);
  --surface-secondary-soft: var(--color-teal-soft);

  --text-primary: var(--color-ink);
  --text-secondary: var(--color-ink-secondary);
  --text-muted: var(--color-ink-muted);
  --text-inverse: var(--color-neutral-0);
  --text-accent: var(--color-accent);
  --text-accent-strong: var(--color-accent-deep);
  --text-link: var(--color-accent);
  --text-link-hover: var(--color-accent-deep);

  --border-default: var(--color-line);
  --border-strong: var(--color-line-strong);

  --action-primary: var(--color-accent);
  --action-primary-hover: var(--color-accent-strong);
  --action-primary-pressed: var(--color-accent-deep);
  --action-primary-on: var(--color-neutral-0);

  --action-secondary: var(--color-teal);
  --action-secondary-hover: var(--color-secondary-500);
  --action-secondary-pressed: var(--color-secondary-600);
  --action-secondary-on: var(--color-teal-deep);

  --focus-ring: 0 0 0 3px rgba(18, 54, 92, 0.35);

  --status-success-bg: var(--color-success-soft);
  --status-success-text: var(--color-success-ink);
  --status-success-border: var(--color-success-border);
  --status-success-solid: var(--color-success-solid);

  --status-warning-bg: var(--color-warning-soft);
  --status-warning-text: var(--color-warning-ink);
  --status-warning-border: var(--color-warning-border);
  --status-warning-solid: var(--color-warning-solid);

  --status-danger-bg: var(--color-danger-soft);
  --status-danger-text: var(--color-danger-ink);
  --status-danger-border: var(--color-danger-border);
  --status-danger-solid: var(--color-danger-solid);

  --status-info-bg: var(--color-info-soft);
  --status-info-text: var(--color-info-ink);
  --status-info-border: var(--color-info-border);
  --status-info-solid: var(--color-info-solid);
}`);

writeFileSync(join(outDir, 'theme.css'), lines.join('\n') + '\n');
console.log('theme.css generated (Tailwind v4 @theme).');